name: Run Agent
on:
  push:
    paths:
      - 'docs/TODO.md'
  workflow_dispatch:

jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install
      - name: Run agent
        run: pnpm ts-node scripts/agent.ts
